http_port 3128

acl connect_method method CONNECT
acl tls_port port 443
acl telegram_oidc dstdomain oauth.telegram.org

http_access deny !connect_method
http_access deny !tls_port
http_access allow telegram_oidc
http_access deny all

cache deny all
cache_log /dev/stderr
cache_mem 8 MB
cache_store_log none
access_log none
pid_filename /tmp/squid.pid
coredump_dir /tmp

forwarded_for delete
workers 1
